export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const REMOVE_FROM_PLAYLIST = 'REMOVE_FROM_PLAYLIST';
export const EDIT_PLAYLIST_TITLE = 'EDIT_PLAYLIST_TITLE';
export const CLEAR_CURRENT_SHOWN_PLAYLIST = 'CLEAR_CURRENT_SHOWN_PLAYLIST';

export const SET_CURRENT_PLAYLIST_SHOWN = 'SET_CURRENT_PLAYLIST_SHOWN';
export const SAVE_PLAYLIST = 'SAVE_PLAYLIST';
export const LOAD_PLAYLIST = 'LOAD_PLAYLIST';